storePassword.debug=skivpn
keyPassword.debug=skivpn
keyAlias.debug=skivpn
storeFile.debug=../private/ski/android/sign/ski.release.keystore
   
storePassword.release=skivpn
keyPassword.release=skivpn
keyAlias.release=skivpn
storeFile.release=../private/ski/android/sign/ski.release.keystore
