storePassword.debug=skivpn
keyPassword.debug=skivpn
keyAlias.debug=skivpn
storeFile.debug=../../private_for_build/ski/ski/android/sign/ski.release.keystore
   
storePassword.release=skivpn
keyPassword.release=skivpn
keyAlias.release=skivpn
storeFile.release=../../private_for_build/ski/ski/android/sign/ski.release.keystore
